# Generated by Django 5.0.6 on 2024-06-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_image_alter_producto_estado_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Precio',
            new_name='precio',
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='media/db-img/default.jpg', upload_to='media/db-img/'),
        ),
    ]
