# Generated by Django 5.0.6 on 2024-06-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_precio_producto_precio_alter_producto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='carroceria',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
