# Generated by Django 5.0.6 on 2024-06-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vehiculo_carroceria_vehiculo_combustible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='carroceria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(max_length=50),
        ),
    ]
