# Generated by Django 5.0.6 on 2024-06-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_producto_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
