# Generated by Django 5.0.6 on 2024-07-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_producto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
