# Generated by Django 5.0.6 on 2024-07-01 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_producto_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accesorios',
            new_name='Accesorio',
        ),
    ]
