# Generated by Django 5.0.6 on 2024-07-02 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_accesorios_accesorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordenVenta',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='venta_producto',
            name='producto_id',
        ),
        migrations.RemoveField(
            model_name='venta_producto',
            name='venta_id',
        ),
        migrations.CreateModel(
            name='detalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.DeleteModel(
            name='Venta_Producto',
        ),
    ]
