# Generated by Django 5.0.6 on 2024-07-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ordenventa_remove_venta_producto_producto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='producto',
        ),
        migrations.DeleteModel(
            name='ordenVenta',
        ),
        migrations.DeleteModel(
            name='detalleOrden',
        ),
    ]
