# Generated by Django 5.0.6 on 2024-07-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tipo_pago',
            field=models.TextField(default='Efectivo', max_length=50),
        ),
    ]
