# Generated by Django 5.0.6 on 2024-07-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_factura_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo_pago',
            field=models.TextField(max_length=50),
        ),
    ]
