# Generated by Django 5.0.6 on 2024-06-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vehiculo_anio_alter_vehiculo_carroceria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(),
        ),
    ]
