# Generated by Django 5.0.6 on 2024-06-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usuario_usuario_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(default='cliente', max_length=50),
        ),
    ]
