# Generated by Django 5.0.6 on 2024-06-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contacto_alter_venta_cliente_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='media/db-img/default.jpg', upload_to='media/db-img/'),
        ),
    ]
